### ISSUE TITLE
Error - cannot make plots 

### ISSUE THREAD

**Issue by mariaUCL** [interactivereport/cellxgene_VIP#101]
When I run cellxgene I get the button and everythiing but when I try to make a violin plot or any other plot I get an error. This is what I get after running cellxgene launch --host localhost --port 5005 --disable-annotations -var feature_name --verbose https://datasets.cellxgene.cziscience.com/676c47a4-bd2c-4f09-82cb-2dfcd54be04a.h5ad :

> ERROR @server: Traceback (most recent call last):
> File "/Users/usr/anaconda3/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 62, in route
> setTimeStamp(data)
> File "/Users/usr/anaconda3/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 1501, in setTimeStamp
> Path(strF).touch()
> File "/Users/usr/anaconda3/envs/VIP/lib/python3.8/pathlib.py", line 1274, in touch
> fd = self._raw_open(flags, mode)
> File "/Users/usr/anaconda3/envs/VIP/lib/python3.8/pathlib.py", line 1083, in _raw_open
> return self._accessor.open(self, flags, mode)
> FileNotFoundError: [Errno 2] No such file or directory: 'https:/datasets.cellxgene.cziscience.com/676c47a4-bd2c-4f09-82cb-2dfcd54be04a.timestamp'

Someone suggested I might not have the necessary R packages but I don't think this is it. I also ran R -q -e 'installed.packages()' to check that I have all the packages which I do. I am not sure what is causing this. I got errors installing hexbin and Cairo so installed them with the below code and still I am getting this error:

> R -q -e 'install.packages("hexbin", repos = "http://bioconductor.org/biocLite.R")'
> R -q -e 'install.packages("hexbin", repos = "http://cran.us.r-project.org/", INSTALL_opts = "--build")'
> brew install Cairo

See packages below:
devtools version: 2.4.5

> check_and_print_version("Cairo")
> Cairo is not installed.
> check_and_print_version("foreign")
> foreign version: 0.8.86
> check_and_print_version("ggpubr")
> ggpubr version: 0.6.0
> check_and_print_version("ggrastr")
> ggrastr version: 1.0.2
> check_and_print_version("arrow")
> arrow version: 14.0.0.2
> check_and_print_version("Seurat")
> Seurat version: 5.0.1
> check_and_print_version("rmarkdown")
> rmarkdown version: 2.25
> check_and_print_version("tidyverse")
> tidyverse version: 2.0.0
> check_and_print_version("viridis")
> viridis version: 0.6.4
> check_and_print_version("hexbin")
> hexbin version: 1.28.3
> check_and_print_version("ggforce")
> ggforce version: 0.4.1
> check_and_print_version("RcppRoll")
> RcppRoll version: 0.3.0
> check_and_print_version("fastmatch")
> fastmatch version: 1.1.4
> check_and_print_version("BiocManager")
> BiocManager version: 1.30.22
> check_and_print_version("fgsea")
> fgsea version: 1.28.0
> check_and_print_version("rtracklayer")
> rtracklayer version: 1.62.0
> check_and_print_version("rjson")
> rjson version: 0.2.21
> check_and_print_version("ComplexHeatmap")
> ComplexHeatmap version: 2.18.0
> check_and_print_version("dbplyr")
> dbplyr version: 2.4.0
> check_and_print_version("RColorBrewer")
> RColorBrewer version: 1.1.3
> check_and_print_version("glue")
> glue version: 1.6.2
> check_and_print_version("gridExtra")
> gridExtra version: 2.3
> check_and_print_version("ggrepel")
> ggrepel version: 0.9.4
> check_and_print_version("MASS")
> MASS version: 7.3.60
> check_and_print_version("data.table")
> data.table version: 1.14.8

**Comment by z5ouyang** [comment]
Please checkout the newest commit and update.VIPInterface.sh. Let me know if the issue still persists.
