### ISSUE TITLE
Missing server.app.VIPInterface

### ISSUE THREAD

**Issue by dfermin** [interactivereport/cellxgene_VIP#60]
Hello. 
I'm trying to install cellxgene_VIP on an Apple laptop running MacOS  11.6.1

I've gotten the entire install process to complete with a few tweaks of the `config.macOS.sh` script.

However when I try to start cellxgene with:
```
cellxgene launch --port 5005 ~/Desktop/pbmc_3K.h5ad
```

I get this error message:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/cellxgene", line 11, in <module>
    load_entry_point('cellxgene==0.16.8', 'console_scripts', 'cellxgene')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/server/cli/cli.py", line 4, in <module>
    from .launch import launch
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/server/cli/launch.py", line 12, in <module>
    from server.app.app import Server
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/server/app/app.py", line 461, in <module>
    from server.app.VIPInterface import route
ModuleNotFoundError: No module named 'server.app.VIPInterface'
```

I think The config.macOS.sh script failed to copy over a python file.
Any suggestions would be greatly appreciated.

Thanks in advance!

**Comment by z5ouyang** [comment]
not sure what have you changed on the ```config.macOS.sh```, seems your changes caused this. The mac install script was tested successfully on 11.6. If you can share what changes have you made, it would be a great help!

**Comment by z5ouyang** [comment]
Since haven't heard back for a long while, I am closing this one.
