### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2' 

### ISSUE THREAD

**Issue by alexlenail** [interactivereport/cellxgene_VIP#84]
```
Execution halted
Traceback (most recent call last):
  File "/Users/alex/miniconda3/envs/VIP/bin/cellxgene", line 5, in <module>
    from server.cli.cli import cli
  File "/Users/alex/miniconda3/envs/VIP/lib/python3.8/site-packages/server/__init__.py", line 3, in <module>
    from server.common.utils.utils import import_plugins
  File "/Users/alex/miniconda3/envs/VIP/lib/python3.8/site-packages/server/common/utils/utils.py", line 11, in <module>
    from flask import json
  File "/Users/alex/miniconda3/envs/VIP/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/Users/alex/miniconda3/envs/VIP/lib/python3.8/site-packages/jinja2/__init__.py)
```

Appears to be fix-able if you update the flask dependency

**Comment by z5ouyang** [comment]
Please reopen if there is still an issue.
