### ISSUE TITLE
Heatmap plotting doesn’t work

### ISSUE THREAD

**Issue by nikhil-elucidata** [interactivereport/cellxgene_VIP#99]
1. <img width="1439" alt="Screenshot 2023-09-29 at 2 41 12 AM" src="https://github.com/interactivereport/cellxgene_VIP/assets/97433046/f1bc6f99-f7da-40cd-a07f-803430d1693a">

ERROR @server: Traceback (most recent call last):
  File "/opt/conda/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 63, in route
    taskRes = distributeTask(data["method"])(data)
  File "/opt/conda/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 713, in pHeatmap
    res = subprocess.run(cmd,check=True,shell=True,capture_output=True)#
  File "/opt/conda/envs/VIP/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/opt/conda/envs/VIP/lib/python3.8/site-packages/server/app/complexHeatmap.R /tmp/HEAT1695935768.375450.csv LTB,HINT1 Expression louvain 6 8 Reds 5 -4 png 11 150 F Yes ''' returned non-zero exit status 1.
2.  <img width="1116" alt="Screenshot 2023-09-29 at 2 51 42 AM" src="https://github.com/interactivereport/cellxgene_VIP/assets/97433046/fc317ef1-9362-4ccf-b7c7-e20681dab9db">

ERROR @server: Traceback (most recent call last):
  File "/opt/conda/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 63, in route
    taskRes = distributeTask(data["method"])(data)
  File "/opt/conda/envs/VIP/lib/python3.8/site-packages/server/app/VIPInterface.py", line 1401, in DENS2D
    raise SyntaxError("in R: "+res.stderr.decode('utf-8'))
  File "<string>", line None
SyntaxError: in R: Error: ggplot2, dplyr and MASS are required R package!
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ggplot2’
Execution halted

**Comment by interactivereport** [comment]
Please make sure that you have all R packages installed @ step 5.
